title: CSS Advanced2
email: elena_karakova@mail.bg
description: Hi there!
destination: docs
baseurl: "/css-advanced-2020" 
url: "" 
twitter_username: 
github_username:  ElenaKarakova

# Build settings
plugins:
  - jekyll-feed


 exclude:
   - docs/
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
